version: '3'
services:

  server:
    image: ghcr.io/cevo-public/cov-spectrum-server:public
    container_name: cov-spectrum-server
    restart: unless-stopped
    environment:
      - COV_SPECTRUM_JWT_SECRET=
      - COV_SPECTRUM_JWT_TOKEN_LIFETIME_SECONDS=172800
      - COV_SPECTRUM_HOST=
      - COV_SPECTRUM_PORT=
      - COV_SPECTRUM_NAME=
      - COV_SPECTRUM_USERNAME=
      - COV_SPECTRUM_PASSWORD=
      - COV_SPECTRUM_GEO_LITE2_DB_PATH=/app/GeoLite2-City.mmdb
    volumes:
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb

  website:
    image: ghcr.io/cevo-public/cov-spectrum-website:public
    container_name: cov-spectrum-website
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: cov-spectrum-nginx
    depends_on:
      - server
      - website
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-cov-spectrum-compose.conf:/etc/nginx/conf.d/default.conf

  # External models

  model-chen2021Fitness:
    image: ghcr.io/cevo-public/cov-spectrum-chen2021fitness:public
    container_name: cov-spectrum-chen2021fitness
    restart: unless-stopped
    ports:
      - "7070:7070"
