version: '3'
services:

  server:
    image: ghcr.io/cevo-public/cov-spectrum-server:public
    container_name: cov-spectrum-server
    restart: unless-stopped
    environment:
      - COV_SPECTRUM_JWT_SECRET=
      - COV_SPECTRUM_JWT_TOKEN_LIFETIME_SECONDS=172800
      - COV_SPECTRUM_HOST=
      - COV_SPECTRUM_PORT=
      - COV_SPECTRUM_NAME=
      - COV_SPECTRUM_USERNAME=
      - COV_SPECTRUM_PASSWORD=

  website:
    image: ghcr.io/cevo-public/cov-spectrum-website:public
    container_name: cov-spectrum-website
    restart: unless-stopped

  nginx:
    image: registry.ethz.ch/sars_cov_2/third-party-containers:nginx
    container_name: cov-spectrum-nginx
    depends_on:
      - server
      - website
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-cov-spectrum-compose.conf:/etc/nginx/conf.d/default.conf

  # External models

  model-chen2021Fitness:
    image: ghcr.io/cevo-public/cov-spectrum-server:model-chen2021Fitness-public
    container_name: cov-spectrum-model-chen2021Fitness
    restart: unless-stopped
