version: '3'
services:

  server:
    image: ghcr.io/cevo-public/cov-spectrum-server:public
    container_name: cov-spectrum-server
    restart: unless-stopped
    environment:
      - COV_SPECTRUM_JWT_SECRET=
      - COV_SPECTRUM_JWT_TOKEN_LIFETIME_SECONDS=172800
      - COV_SPECTRUM_DB_HOST=
      - COV_SPECTRUM_DB_PORT=5432
      - COV_SPECTRUM_DB_NAME=covspectrum
      - COV_SPECTRUM_DB_USERNAME=
      - COV_SPECTRUM_DB_PASSWORD=
      - COV_SPECTRUM_GEO_LITE2_DB_PATH=/app/GeoLite2-City.mmdb
    volumes:
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb

  nginx:
    image: nginx:stable
    container_name: cov-spectrum-server-nginx
    depends_on:
      - server
      - model-huisman_scire2021re
      - model-chen2021Fitness
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx-cov-spectrum-compose.conf:/etc/nginx/conf.d/default.conf

  # External models

  model-chen2021Fitness:
    image: ghcr.io/cevo-public/cov-spectrum-chen2021fitness:public
    container_name: cov-spectrum-server-chen2021fitness
    restart: unless-stopped

  model-huisman_scire2021re:
    image: ghcr.io/cevo-public/cov-spectrum-huisman_scire2021re:public
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 4
