version: '3'
services:

  server:
    image: registry.ethz.ch/sars_cov_2/variant-monitor-server:latest
    container_name: variant-monitor-server
    restart: unless-stopped
    environment:
      - VM_DB_HOST=
      - VM_DB_PORT=
      - VM_DB_NAME=
      - VM_DB_USERNAME=
      - VM_DB_PASSWORD=

  website:
    image: registry.ethz.ch/sars_cov_2/variant-monitor-website:latest
    container_name: variant-monitor-website
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: variant-monitor-nginx
    depends_on:
      - server
      - website
    restart: unless-stopped
    ports:
      - "7000:80"
    volumes:
      - ./nginx-variant-monitor-compose.conf:/etc/nginx/conf.d/default.conf
