/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.covspectrum.tables.ConsensusSequence;
import org.jooq.covspectrum.tables.GisaidSequence;
import org.jooq.covspectrum.tables.SpectrumSequencePrivateMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePrivateMutationAa;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMutationAa;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSENSUS_SEQUENCE_ETHID_INDEX = Internal.createIndex(DSL.name("consensus_sequence_ethid_index"), ConsensusSequence.CONSENSUS_SEQUENCE, new OrderField[] { ConsensusSequence.CONSENSUS_SEQUENCE.ETHID }, false);
    public static final Index GISAID_SEQUENCE_AGE_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_age_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.AGE }, false);
    public static final Index GISAID_SEQUENCE_COUNTRY_EXPOSURE_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_country_exposure_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.COUNTRY_EXPOSURE }, false);
    public static final Index GISAID_SEQUENCE_COUNTRY_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_country_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.COUNTRY }, false);
    public static final Index GISAID_SEQUENCE_DATE_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_date_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.DATE }, false);
    public static final Index GISAID_SEQUENCE_DATE_SUBMITTED_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_date_submitted_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.DATE_SUBMITTED }, false);
    public static final Index GISAID_SEQUENCE_DIVISION_EXPOSURE_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_division_exposure_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.DIVISION_EXPOSURE }, false);
    public static final Index GISAID_SEQUENCE_DIVISION_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_division_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.DIVISION }, false);
    public static final Index GISAID_SEQUENCE_GISAID_EPI_ISL_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_gisaid_epi_isl_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.GISAID_EPI_ISL }, false);
    public static final Index GISAID_SEQUENCE_HOST_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_host_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.HOST }, false);
    public static final Index GISAID_SEQUENCE_ORIGINATING_LAB_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_originating_lab_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.ORIGINATING_LAB }, false);
    public static final Index GISAID_SEQUENCE_REGION_EXPOSURE_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_region_exposure_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.REGION_EXPOSURE }, false);
    public static final Index GISAID_SEQUENCE_REGION_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_region_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.REGION }, false);
    public static final Index GISAID_SEQUENCE_SEX_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_sex_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.SEX }, false);
    public static final Index GISAID_SEQUENCE_SUBMITTING_LAB_INDEX2 = Internal.createIndex(DSL.name("gisaid_sequence_submitting_lab_index2"), GisaidSequence.GISAID_SEQUENCE, new OrderField[] { GisaidSequence.GISAID_SEQUENCE.SUBMITTING_LAB }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_AGE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_age_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.AGE }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_COUNTRY_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_country_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.COUNTRY }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_DATE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_date_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.DATE }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_DIVISION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_division_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.DIVISION }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_HOST_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_host_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.HOST }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_LOCATION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_location_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.LOCATION }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_REGION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_region_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.REGION }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_SEQUENCE_NAME_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_sequence_name_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.SEQUENCE_NAME }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_SEX_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_sex_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.SEX }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_META_ZIP_CODE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_meta_zip_code_idx"), SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META, new OrderField[] { SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META.ZIP_CODE }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA_AA_MUTATION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_mutation_aa_aa_mutation_idx"), SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA, new OrderField[] { SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA.AA_MUTATION }, false);
    public static final Index SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA_SEQUENCE_NAME_IDX = Internal.createIndex(DSL.name("spectrum_sequence_private_mutation_aa_sequence_name_idx"), SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA, new OrderField[] { SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA.SEQUENCE_NAME }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_AGE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_age_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.AGE }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_COUNTRY_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_country_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.COUNTRY }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_DATE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_date_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.DATE }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_DIVISION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_division_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.DIVISION }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_HOST_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_host_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.HOST }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_LOCATION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_location_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.LOCATION }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_REGION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_region_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.REGION }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_SEQUENCE_NAME_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_sequence_name_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.SEQUENCE_NAME }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_SEX_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_sex_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.SEX }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_META_ZIP_CODE_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_meta_zip_code_idx"), SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META, new OrderField[] { SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META.ZIP_CODE }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA_AA_MUTATION_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_mutation_aa_aa_mutation_idx"), SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA, new OrderField[] { SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION }, false);
    public static final Index SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA_SEQUENCE_NAME_IDX = Internal.createIndex(DSL.name("spectrum_sequence_public_mutation_aa_sequence_name_idx"), SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA, new OrderField[] { SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.SEQUENCE_NAME }, false);
}
