/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.covspectrum.tables.ConsensusSequence;
import org.jooq.covspectrum.tables.GisaidSequence;
import org.jooq.covspectrum.tables.SpectrumAccount;
import org.jooq.covspectrum.tables.SpectrumNewInterestingVariant;
import org.jooq.covspectrum.tables.VariantMutationAa;
import org.jooq.covspectrum.tables.VariantMutationNucleotide;
import org.jooq.covspectrum.tables.records.ConsensusSequenceRecord;
import org.jooq.covspectrum.tables.records.GisaidSequenceRecord;
import org.jooq.covspectrum.tables.records.SpectrumAccountRecord;
import org.jooq.covspectrum.tables.records.SpectrumNewInterestingVariantRecord;
import org.jooq.covspectrum.tables.records.VariantMutationAaRecord;
import org.jooq.covspectrum.tables.records.VariantMutationNucleotideRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConsensusSequenceRecord> CONSENSUS_SEQUENCE_PKEY = Internal.createUniqueKey(ConsensusSequence.CONSENSUS_SEQUENCE, DSL.name("consensus_sequence_pkey"), new TableField[] { ConsensusSequence.CONSENSUS_SEQUENCE.SAMPLE_NAME }, true);
    public static final UniqueKey<GisaidSequenceRecord> GISAID_SEQUENCE_PKEY = Internal.createUniqueKey(GisaidSequence.GISAID_SEQUENCE, DSL.name("gisaid_sequence_pkey"), new TableField[] { GisaidSequence.GISAID_SEQUENCE.STRAIN }, true);
    public static final UniqueKey<SpectrumAccountRecord> SPECTRUM_ACCOUNT_PKEY = Internal.createUniqueKey(SpectrumAccount.SPECTRUM_ACCOUNT, DSL.name("spectrum_account_pkey"), new TableField[] { SpectrumAccount.SPECTRUM_ACCOUNT.USERNAME }, true);
    public static final UniqueKey<SpectrumNewInterestingVariantRecord> SPECTRUM_NEW_INTERESTING_VARIANT_PKEY = Internal.createUniqueKey(SpectrumNewInterestingVariant.SPECTRUM_NEW_INTERESTING_VARIANT, DSL.name("spectrum_new_interesting_variant_pkey"), new TableField[] { SpectrumNewInterestingVariant.SPECTRUM_NEW_INTERESTING_VARIANT.ID }, true);
    public static final UniqueKey<VariantMutationAaRecord> VARIANT_MUTATION_AA_PKEY = Internal.createUniqueKey(VariantMutationAa.VARIANT_MUTATION_AA, DSL.name("variant_mutation_aa_pkey"), new TableField[] { VariantMutationAa.VARIANT_MUTATION_AA.VARIANT_NAME, VariantMutationAa.VARIANT_MUTATION_AA.AA_MUTATION }, true);
    public static final UniqueKey<VariantMutationNucleotideRecord> VARIANT_MUTATION_NUCLEOTIDE_PKEY = Internal.createUniqueKey(VariantMutationNucleotide.VARIANT_MUTATION_NUCLEOTIDE, DSL.name("variant_mutation_nucleotide_pkey"), new TableField[] { VariantMutationNucleotide.VARIANT_MUTATION_NUCLEOTIDE.VARIANT_NAME, VariantMutationNucleotide.VARIANT_MUTATION_NUCLEOTIDE.NUCLEOTIDE_MUTATION }, true);
}
