/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.covspectrum.tables.ConsensusSequence;
import org.jooq.covspectrum.tables.GisaidSequence;
import org.jooq.covspectrum.tables.SpectrumAccount;
import org.jooq.covspectrum.tables.records.ConsensusSequenceRecord;
import org.jooq.covspectrum.tables.records.GisaidSequenceRecord;
import org.jooq.covspectrum.tables.records.SpectrumAccountRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConsensusSequenceRecord> CONSENSUS_SEQUENCE_PKEY = Internal.createUniqueKey(ConsensusSequence.CONSENSUS_SEQUENCE, DSL.name("consensus_sequence_pkey"), new TableField[] { ConsensusSequence.CONSENSUS_SEQUENCE.SAMPLE_NAME }, true);
    public static final UniqueKey<GisaidSequenceRecord> GISAID_SEQUENCE_STAGING_PKEY = Internal.createUniqueKey(GisaidSequence.GISAID_SEQUENCE, DSL.name("gisaid_sequence_staging_pkey"), new TableField[] { GisaidSequence.GISAID_SEQUENCE.STRAIN }, true);
    public static final UniqueKey<SpectrumAccountRecord> SPECTRUM_ACCOUNT_PKEY = Internal.createUniqueKey(SpectrumAccount.SPECTRUM_ACCOUNT, DSL.name("spectrum_account_pkey"), new TableField[] { SpectrumAccount.SPECTRUM_ACCOUNT.USERNAME }, true);
}
