/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.covspectrum.tables.ConsensusSequence;
import org.jooq.covspectrum.tables.GisaidSequence;
import org.jooq.covspectrum.tables.SpectrumAccount;
import org.jooq.covspectrum.tables.SpectrumSequenceIntensity;
import org.jooq.covspectrum.tables.SpectrumSequencePrivateMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePrivateMutationAa;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMutationAa;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.consensus_sequence</code>.
     */
    public final ConsensusSequence CONSENSUS_SEQUENCE = ConsensusSequence.CONSENSUS_SEQUENCE;

    /**
     * The table <code>public.gisaid_sequence</code>.
     */
    public final GisaidSequence GISAID_SEQUENCE = GisaidSequence.GISAID_SEQUENCE;

    /**
     * The table <code>public.spectrum_account</code>.
     */
    public final SpectrumAccount SPECTRUM_ACCOUNT = SpectrumAccount.SPECTRUM_ACCOUNT;

    /**
     * The table <code>public.spectrum_sequence_intensity</code>.
     */
    public final SpectrumSequenceIntensity SPECTRUM_SEQUENCE_INTENSITY = SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY;

    /**
     * The table <code>public.spectrum_sequence_private_meta</code>.
     */
    public final SpectrumSequencePrivateMeta SPECTRUM_SEQUENCE_PRIVATE_META = SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META;

    /**
     * The table <code>public.spectrum_sequence_private_mutation_aa</code>.
     */
    public final SpectrumSequencePrivateMutationAa SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA = SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA;

    /**
     * The table <code>public.spectrum_sequence_public_meta</code>.
     */
    public final SpectrumSequencePublicMeta SPECTRUM_SEQUENCE_PUBLIC_META = SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META;

    /**
     * The table <code>public.spectrum_sequence_public_mutation_aa</code>.
     */
    public final SpectrumSequencePublicMutationAa SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA = SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ConsensusSequence.CONSENSUS_SEQUENCE,
            GisaidSequence.GISAID_SEQUENCE,
            SpectrumAccount.SPECTRUM_ACCOUNT,
            SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY,
            SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META,
            SpectrumSequencePrivateMutationAa.SPECTRUM_SEQUENCE_PRIVATE_MUTATION_AA,
            SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META,
            SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA);
    }
}
