/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.covspectrum.tables.ConsensusSequence;
import org.jooq.covspectrum.tables.GisaidSequence;
import org.jooq.covspectrum.tables.SpectrumAccount;
import org.jooq.covspectrum.tables.SpectrumApiCacheSample;
import org.jooq.covspectrum.tables.SpectrumApiUsageSample;
import org.jooq.covspectrum.tables.SpectrumCountry;
import org.jooq.covspectrum.tables.SpectrumNewInterestingVariant;
import org.jooq.covspectrum.tables.SpectrumSequenceIntensity;
import org.jooq.covspectrum.tables.SpectrumSequencePrivateMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMeta;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMutationAa;
import org.jooq.covspectrum.tables.VariantMutationAa;
import org.jooq.covspectrum.tables.VariantMutationNucleotide;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.consensus_sequence</code>.
     */
    public final ConsensusSequence CONSENSUS_SEQUENCE = ConsensusSequence.CONSENSUS_SEQUENCE;

    /**
     * The table <code>public.gisaid_sequence</code>.
     */
    public final GisaidSequence GISAID_SEQUENCE = GisaidSequence.GISAID_SEQUENCE;

    /**
     * The table <code>public.spectrum_account</code>.
     */
    public final SpectrumAccount SPECTRUM_ACCOUNT = SpectrumAccount.SPECTRUM_ACCOUNT;

    /**
     * The table <code>public.spectrum_api_cache_sample</code>.
     */
    public final SpectrumApiCacheSample SPECTRUM_API_CACHE_SAMPLE = SpectrumApiCacheSample.SPECTRUM_API_CACHE_SAMPLE;

    /**
     * The table <code>public.spectrum_api_usage_sample</code>.
     */
    public final SpectrumApiUsageSample SPECTRUM_API_USAGE_SAMPLE = SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE;

    /**
     * The table <code>public.spectrum_country</code>.
     */
    public final SpectrumCountry SPECTRUM_COUNTRY = SpectrumCountry.SPECTRUM_COUNTRY;

    /**
     * The table <code>public.spectrum_new_interesting_variant</code>.
     */
    public final SpectrumNewInterestingVariant SPECTRUM_NEW_INTERESTING_VARIANT = SpectrumNewInterestingVariant.SPECTRUM_NEW_INTERESTING_VARIANT;

    /**
     * The table <code>public.spectrum_sequence_intensity</code>.
     */
    public final SpectrumSequenceIntensity SPECTRUM_SEQUENCE_INTENSITY = SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY;

    /**
     * The table <code>public.spectrum_sequence_private_meta</code>.
     */
    public final SpectrumSequencePrivateMeta SPECTRUM_SEQUENCE_PRIVATE_META = SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META;

    /**
     * The table <code>public.spectrum_sequence_public_meta</code>.
     */
    public final SpectrumSequencePublicMeta SPECTRUM_SEQUENCE_PUBLIC_META = SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META;

    /**
     * The table <code>public.spectrum_sequence_public_mutation_aa</code>.
     */
    public final SpectrumSequencePublicMutationAa SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA = SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA;

    /**
     * The table <code>public.variant_mutation_aa</code>.
     */
    public final VariantMutationAa VARIANT_MUTATION_AA = VariantMutationAa.VARIANT_MUTATION_AA;

    /**
     * The table <code>public.variant_mutation_nucleotide</code>.
     */
    public final VariantMutationNucleotide VARIANT_MUTATION_NUCLEOTIDE = VariantMutationNucleotide.VARIANT_MUTATION_NUCLEOTIDE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SPECTRUM_API_CACHE_SAMPLE_ID_SEQ,
            Sequences.SPECTRUM_API_USAGE_SAMPLE_ID_SEQ,
            Sequences.SPECTRUM_NEW_INTERESTING_VARIANT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ConsensusSequence.CONSENSUS_SEQUENCE,
            GisaidSequence.GISAID_SEQUENCE,
            SpectrumAccount.SPECTRUM_ACCOUNT,
            SpectrumApiCacheSample.SPECTRUM_API_CACHE_SAMPLE,
            SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE,
            SpectrumCountry.SPECTRUM_COUNTRY,
            SpectrumNewInterestingVariant.SPECTRUM_NEW_INTERESTING_VARIANT,
            SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY,
            SpectrumSequencePrivateMeta.SPECTRUM_SEQUENCE_PRIVATE_META,
            SpectrumSequencePublicMeta.SPECTRUM_SEQUENCE_PUBLIC_META,
            SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA,
            VariantMutationAa.VARIANT_MUTATION_AA,
            VariantMutationNucleotide.VARIANT_MUTATION_NUCLEOTIDE);
    }
}
