/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.covspectrum.tables.SpectrumCases
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC = Public()
    }

    /**
     * The table <code>public.spectrum_cases</code>.
     */
    val SPECTRUM_CASES get() = SpectrumCases.SPECTRUM_CASES

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        SpectrumCases.SPECTRUM_CASES
    )
}
