/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.covspectrum.tables.Cases
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.cases</code>.
     */
    val CASES: Cases get() = Cases.CASES

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Cases.CASES
    )
}
