/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.PangolinLineage_PubmedArticleRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PangolinLineage_PubmedArticle extends TableImpl<PangolinLineage_PubmedArticleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pangolin_lineage__pubmed_article</code>
     */
    public static final PangolinLineage_PubmedArticle PANGOLIN_LINEAGE__PUBMED_ARTICLE = new PangolinLineage_PubmedArticle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PangolinLineage_PubmedArticleRecord> getRecordType() {
        return PangolinLineage_PubmedArticleRecord.class;
    }

    /**
     * The column <code>public.pangolin_lineage__pubmed_article.pangolin_lineage</code>.
     */
    public final TableField<PangolinLineage_PubmedArticleRecord, String> PANGOLIN_LINEAGE = createField(DSL.name("pangolin_lineage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.pangolin_lineage__pubmed_article.pmid</code>.
     */
    public final TableField<PangolinLineage_PubmedArticleRecord, Long> PMID = createField(DSL.name("pmid"), SQLDataType.BIGINT, this, "");

    private PangolinLineage_PubmedArticle(Name alias, Table<PangolinLineage_PubmedArticleRecord> aliased) {
        this(alias, aliased, null);
    }

    private PangolinLineage_PubmedArticle(Name alias, Table<PangolinLineage_PubmedArticleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    /**
     * Create an aliased <code>public.pangolin_lineage__pubmed_article</code> table reference
     */
    public PangolinLineage_PubmedArticle(String alias) {
        this(DSL.name(alias), PANGOLIN_LINEAGE__PUBMED_ARTICLE);
    }

    /**
     * Create an aliased <code>public.pangolin_lineage__pubmed_article</code> table reference
     */
    public PangolinLineage_PubmedArticle(Name alias) {
        this(alias, PANGOLIN_LINEAGE__PUBMED_ARTICLE);
    }

    /**
     * Create a <code>public.pangolin_lineage__pubmed_article</code> table reference
     */
    public PangolinLineage_PubmedArticle() {
        this(DSL.name("pangolin_lineage__pubmed_article"), null);
    }

    public <O extends Record> PangolinLineage_PubmedArticle(Table<O> child, ForeignKey<O, PangolinLineage_PubmedArticleRecord> key) {
        super(child, key, PANGOLIN_LINEAGE__PUBMED_ARTICLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public PangolinLineage_PubmedArticle as(String alias) {
        return new PangolinLineage_PubmedArticle(DSL.name(alias), this);
    }

    @Override
    public PangolinLineage_PubmedArticle as(Name alias) {
        return new PangolinLineage_PubmedArticle(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PangolinLineage_PubmedArticle rename(String name) {
        return new PangolinLineage_PubmedArticle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PangolinLineage_PubmedArticle rename(Name name) {
        return new PangolinLineage_PubmedArticle(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
