/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.covspectrum.Keys;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.SpectrumCountryRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumCountry extends TableImpl<SpectrumCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spectrum_country</code>
     */
    public static final SpectrumCountry SPECTRUM_COUNTRY = new SpectrumCountry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpectrumCountryRecord> getRecordType() {
        return SpectrumCountryRecord.class;
    }

    /**
     * The column <code>public.spectrum_country.iso_code</code>.
     */
    public final TableField<SpectrumCountryRecord, String> ISO_CODE = createField(DSL.name("iso_code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_country.name</code>.
     */
    public final TableField<SpectrumCountryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_country.region</code>.
     */
    public final TableField<SpectrumCountryRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_country.url_component</code>.
     */
    public final TableField<SpectrumCountryRecord, String> URL_COMPONENT = createField(DSL.name("url_component"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_country.fiv_resource_category</code>.
     */
    public final TableField<SpectrumCountryRecord, String> FIV_RESOURCE_CATEGORY = createField(DSL.name("fiv_resource_category"), SQLDataType.CLOB, this, "");

    private SpectrumCountry(Name alias, Table<SpectrumCountryRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpectrumCountry(Name alias, Table<SpectrumCountryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.spectrum_country</code> table reference
     */
    public SpectrumCountry(String alias) {
        this(DSL.name(alias), SPECTRUM_COUNTRY);
    }

    /**
     * Create an aliased <code>public.spectrum_country</code> table reference
     */
    public SpectrumCountry(Name alias) {
        this(alias, SPECTRUM_COUNTRY);
    }

    /**
     * Create a <code>public.spectrum_country</code> table reference
     */
    public SpectrumCountry() {
        this(DSL.name("spectrum_country"), null);
    }

    public <O extends Record> SpectrumCountry(Table<O> child, ForeignKey<O, SpectrumCountryRecord> key) {
        super(child, key, SPECTRUM_COUNTRY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpectrumCountryRecord> getPrimaryKey() {
        return Keys.SPECTRUM_COUNTRY_PKEY;
    }

    @Override
    public List<UniqueKey<SpectrumCountryRecord>> getKeys() {
        return Arrays.<UniqueKey<SpectrumCountryRecord>>asList(Keys.SPECTRUM_COUNTRY_PKEY, Keys.SPECTRUM_COUNTRY_NAME_KEY, Keys.SPECTRUM_COUNTRY_URL_COMPONENT_KEY);
    }

    @Override
    public SpectrumCountry as(String alias) {
        return new SpectrumCountry(DSL.name(alias), this);
    }

    @Override
    public SpectrumCountry as(Name alias) {
        return new SpectrumCountry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumCountry rename(String name) {
        return new SpectrumCountry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumCountry rename(Name name) {
        return new SpectrumCountry(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
