/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.covspectrum.Keys;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.SpectrumPangolinLineageRecentMetricsRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumPangolinLineageRecentMetrics extends TableImpl<SpectrumPangolinLineageRecentMetricsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spectrum_pangolin_lineage_recent_metrics</code>
     */
    public static final SpectrumPangolinLineageRecentMetrics SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS = new SpectrumPangolinLineageRecentMetrics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpectrumPangolinLineageRecentMetricsRecord> getRecordType() {
        return SpectrumPangolinLineageRecentMetricsRecord.class;
    }

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.id</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.insertion_timestamp</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, LocalDateTime> INSERTION_TIMESTAMP = createField(DSL.name("insertion_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.pangolin_lineage</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, String> PANGOLIN_LINEAGE = createField(DSL.name("pangolin_lineage"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.region</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.country</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.fitness_advantage</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, Double> FITNESS_ADVANTAGE = createField(DSL.name("fitness_advantage"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.fitness_advantage_lower</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, Double> FITNESS_ADVANTAGE_LOWER = createField(DSL.name("fitness_advantage_lower"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_pangolin_lineage_recent_metrics.fitness_advantage_upper</code>.
     */
    public final TableField<SpectrumPangolinLineageRecentMetricsRecord, Double> FITNESS_ADVANTAGE_UPPER = createField(DSL.name("fitness_advantage_upper"), SQLDataType.DOUBLE.nullable(false), this, "");

    private SpectrumPangolinLineageRecentMetrics(Name alias, Table<SpectrumPangolinLineageRecentMetricsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpectrumPangolinLineageRecentMetrics(Name alias, Table<SpectrumPangolinLineageRecentMetricsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.spectrum_pangolin_lineage_recent_metrics</code> table reference
     */
    public SpectrumPangolinLineageRecentMetrics(String alias) {
        this(DSL.name(alias), SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS);
    }

    /**
     * Create an aliased <code>public.spectrum_pangolin_lineage_recent_metrics</code> table reference
     */
    public SpectrumPangolinLineageRecentMetrics(Name alias) {
        this(alias, SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS);
    }

    /**
     * Create a <code>public.spectrum_pangolin_lineage_recent_metrics</code> table reference
     */
    public SpectrumPangolinLineageRecentMetrics() {
        this(DSL.name("spectrum_pangolin_lineage_recent_metrics"), null);
    }

    public <O extends Record> SpectrumPangolinLineageRecentMetrics(Table<O> child, ForeignKey<O, SpectrumPangolinLineageRecentMetricsRecord> key) {
        super(child, key, SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<SpectrumPangolinLineageRecentMetricsRecord, Integer> getIdentity() {
        return (Identity<SpectrumPangolinLineageRecentMetricsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SpectrumPangolinLineageRecentMetricsRecord> getPrimaryKey() {
        return Keys.SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS_PKEY;
    }

    @Override
    public List<UniqueKey<SpectrumPangolinLineageRecentMetricsRecord>> getKeys() {
        return Arrays.<UniqueKey<SpectrumPangolinLineageRecentMetricsRecord>>asList(Keys.SPECTRUM_PANGOLIN_LINEAGE_RECENT_METRICS_PKEY);
    }

    @Override
    public SpectrumPangolinLineageRecentMetrics as(String alias) {
        return new SpectrumPangolinLineageRecentMetrics(DSL.name(alias), this);
    }

    @Override
    public SpectrumPangolinLineageRecentMetrics as(Name alias) {
        return new SpectrumPangolinLineageRecentMetrics(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumPangolinLineageRecentMetrics rename(String name) {
        return new SpectrumPangolinLineageRecentMetrics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumPangolinLineageRecentMetrics rename(Name name) {
        return new SpectrumPangolinLineageRecentMetrics(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, LocalDateTime, String, String, String, Double, Double, Double> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
