/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.covspectrum.Indexes;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.SpectrumSequencePublicMetaRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumSequencePublicMeta extends TableImpl<SpectrumSequencePublicMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spectrum_sequence_public_meta</code>
     */
    public static final SpectrumSequencePublicMeta SPECTRUM_SEQUENCE_PUBLIC_META = new SpectrumSequencePublicMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpectrumSequencePublicMetaRecord> getRecordType() {
        return SpectrumSequencePublicMetaRecord.class;
    }

    /**
     * The column <code>public.spectrum_sequence_public_meta.sequence_name</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> SEQUENCE_NAME = createField(DSL.name("sequence_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.date</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.region</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.country</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.division</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> DIVISION = createField(DSL.name("division"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.location</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.zip_code</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> ZIP_CODE = createField(DSL.name("zip_code"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.host</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.age</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, Integer> AGE = createField(DSL.name("age"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.sex</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> SEX = createField(DSL.name("sex"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.submitting_lab</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> SUBMITTING_LAB = createField(DSL.name("submitting_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.originating_lab</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> ORIGINATING_LAB = createField(DSL.name("originating_lab"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.hospitalized</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, Boolean> HOSPITALIZED = createField(DSL.name("hospitalized"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.deceased</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, Boolean> DECEASED = createField(DSL.name("deceased"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.spectrum_sequence_public_meta.pangolin_lineage</code>.
     */
    public final TableField<SpectrumSequencePublicMetaRecord, String> PANGOLIN_LINEAGE = createField(DSL.name("pangolin_lineage"), SQLDataType.CLOB, this, "");

    private SpectrumSequencePublicMeta(Name alias, Table<SpectrumSequencePublicMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpectrumSequencePublicMeta(Name alias, Table<SpectrumSequencePublicMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    /**
     * Create an aliased <code>public.spectrum_sequence_public_meta</code> table reference
     */
    public SpectrumSequencePublicMeta(String alias) {
        this(DSL.name(alias), SPECTRUM_SEQUENCE_PUBLIC_META);
    }

    /**
     * Create an aliased <code>public.spectrum_sequence_public_meta</code> table reference
     */
    public SpectrumSequencePublicMeta(Name alias) {
        this(alias, SPECTRUM_SEQUENCE_PUBLIC_META);
    }

    /**
     * Create a <code>public.spectrum_sequence_public_meta</code> table reference
     */
    public SpectrumSequencePublicMeta() {
        this(DSL.name("spectrum_sequence_public_meta"), null);
    }

    public <O extends Record> SpectrumSequencePublicMeta(Table<O> child, ForeignKey<O, SpectrumSequencePublicMetaRecord> key) {
        super(child, key, SPECTRUM_SEQUENCE_PUBLIC_META);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_AGE_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_COUNTRY_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_DATE_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_DIVISION_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_HOST_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_LOCATION_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_PANGOLIN_LINEAGE_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_REGION_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_SEQUENCE_NAME_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_SEX_IDX, Indexes.SPECTRUM_SEQUENCE_PUBLIC_META_ZIP_CODE_IDX);
    }

    @Override
    public SpectrumSequencePublicMeta as(String alias) {
        return new SpectrumSequencePublicMeta(DSL.name(alias), this);
    }

    @Override
    public SpectrumSequencePublicMeta as(Name alias) {
        return new SpectrumSequencePublicMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumSequencePublicMeta rename(String name) {
        return new SpectrumSequencePublicMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumSequencePublicMeta rename(Name name) {
        return new SpectrumSequencePublicMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, LocalDate, String, String, String, String, String, String, Integer, String, String, String, Boolean, Boolean, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
