/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.covspectrum.Keys;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.SpectrumWasteWaterResultOldRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumWasteWaterResultOld extends TableImpl<SpectrumWasteWaterResultOldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spectrum_waste_water_result_old</code>
     */
    public static final SpectrumWasteWaterResultOld SPECTRUM_WASTE_WATER_RESULT_OLD = new SpectrumWasteWaterResultOld();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpectrumWasteWaterResultOldRecord> getRecordType() {
        return SpectrumWasteWaterResultOldRecord.class;
    }

    /**
     * The column <code>public.spectrum_waste_water_result_old.variant_name</code>.
     */
    public final TableField<SpectrumWasteWaterResultOldRecord, String> VARIANT_NAME = createField(DSL.name("variant_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.spectrum_waste_water_result_old.data</code>.
     */
    public final TableField<SpectrumWasteWaterResultOldRecord, JSONB> DATA = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    private SpectrumWasteWaterResultOld(Name alias, Table<SpectrumWasteWaterResultOldRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpectrumWasteWaterResultOld(Name alias, Table<SpectrumWasteWaterResultOldRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.spectrum_waste_water_result_old</code> table reference
     */
    public SpectrumWasteWaterResultOld(String alias) {
        this(DSL.name(alias), SPECTRUM_WASTE_WATER_RESULT_OLD);
    }

    /**
     * Create an aliased <code>public.spectrum_waste_water_result_old</code> table reference
     */
    public SpectrumWasteWaterResultOld(Name alias) {
        this(alias, SPECTRUM_WASTE_WATER_RESULT_OLD);
    }

    /**
     * Create a <code>public.spectrum_waste_water_result_old</code> table reference
     */
    public SpectrumWasteWaterResultOld() {
        this(DSL.name("spectrum_waste_water_result_old"), null);
    }

    public <O extends Record> SpectrumWasteWaterResultOld(Table<O> child, ForeignKey<O, SpectrumWasteWaterResultOldRecord> key) {
        super(child, key, SPECTRUM_WASTE_WATER_RESULT_OLD);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<SpectrumWasteWaterResultOldRecord> getPrimaryKey() {
        return Keys.SPECTRUM_WASTE_WATER_RESULTS_PKEY;
    }

    @Override
    public List<UniqueKey<SpectrumWasteWaterResultOldRecord>> getKeys() {
        return Arrays.<UniqueKey<SpectrumWasteWaterResultOldRecord>>asList(Keys.SPECTRUM_WASTE_WATER_RESULTS_PKEY);
    }

    @Override
    public SpectrumWasteWaterResultOld as(String alias) {
        return new SpectrumWasteWaterResultOld(DSL.name(alias), this);
    }

    @Override
    public SpectrumWasteWaterResultOld as(Name alias) {
        return new SpectrumWasteWaterResultOld(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumWasteWaterResultOld rename(String name) {
        return new SpectrumWasteWaterResultOld(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumWasteWaterResultOld rename(Name name) {
        return new SpectrumWasteWaterResultOld(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, JSONB> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
