/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.covspectrum.Indexes;
import org.jooq.covspectrum.Public;
import org.jooq.covspectrum.tables.records.SpectrumSequenceIntensityRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumSequenceIntensity extends TableImpl<SpectrumSequenceIntensityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.spectrum_sequence_intensity</code>
     */
    public static final SpectrumSequenceIntensity SPECTRUM_SEQUENCE_INTENSITY = new SpectrumSequenceIntensity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpectrumSequenceIntensityRecord> getRecordType() {
        return SpectrumSequenceIntensityRecord.class;
    }

    /**
     * The column <code>public.spectrum_sequence_intensity.date</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.spectrum_sequence_intensity.region</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, String> REGION = createField(DSL.name("region"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_intensity.country</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.spectrum_sequence_intensity.cases</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, Long> CASES = createField(DSL.name("cases"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.spectrum_sequence_intensity.sequenced</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, BigDecimal> SEQUENCED = createField(DSL.name("sequenced"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.spectrum_sequence_intensity.sequenced_surveillance</code>.
     */
    public final TableField<SpectrumSequenceIntensityRecord, BigDecimal> SEQUENCED_SURVEILLANCE = createField(DSL.name("sequenced_surveillance"), SQLDataType.NUMERIC, this, "");

    private SpectrumSequenceIntensity(Name alias, Table<SpectrumSequenceIntensityRecord> aliased) {
        this(alias, aliased, null);
    }

    private SpectrumSequenceIntensity(Name alias, Table<SpectrumSequenceIntensityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    /**
     * Create an aliased <code>public.spectrum_sequence_intensity</code> table reference
     */
    public SpectrumSequenceIntensity(String alias) {
        this(DSL.name(alias), SPECTRUM_SEQUENCE_INTENSITY);
    }

    /**
     * Create an aliased <code>public.spectrum_sequence_intensity</code> table reference
     */
    public SpectrumSequenceIntensity(Name alias) {
        this(alias, SPECTRUM_SEQUENCE_INTENSITY);
    }

    /**
     * Create a <code>public.spectrum_sequence_intensity</code> table reference
     */
    public SpectrumSequenceIntensity() {
        this(DSL.name("spectrum_sequence_intensity"), null);
    }

    public <O extends Record> SpectrumSequenceIntensity(Table<O> child, ForeignKey<O, SpectrumSequenceIntensityRecord> key) {
        super(child, key, SPECTRUM_SEQUENCE_INTENSITY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SPECTRUM_SEQUENCE_INTENSITY_COUNTRY_IDX, Indexes.SPECTRUM_SEQUENCE_INTENSITY_REGION_IDX);
    }

    @Override
    public SpectrumSequenceIntensity as(String alias) {
        return new SpectrumSequenceIntensity(DSL.name(alias), this);
    }

    @Override
    public SpectrumSequenceIntensity as(Name alias) {
        return new SpectrumSequenceIntensity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumSequenceIntensity rename(String name) {
        return new SpectrumSequenceIntensity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpectrumSequenceIntensity rename(Name name) {
        return new SpectrumSequenceIntensity(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<LocalDate, String, String, Long, BigDecimal, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
