/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.keys


import org.jooq.UniqueKey
import org.jooq.covspectrum.tables.ExtOwidGlobalCases
import org.jooq.covspectrum.tables.records.ExtOwidGlobalCasesRecord
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val EXT_OWID_GLOBAL_CASES_PKEY: UniqueKey<ExtOwidGlobalCasesRecord> = Internal.createUniqueKey(ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES, DSL.name("ext_owid_global_cases_pkey"), arrayOf(ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.ISO_COUNTRY, ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.DATE), true)
