/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.references


import org.jooq.covspectrum.tables.SpectrumOwidGlobalCases



/**
 * The table <code>public.spectrum_owid_global_cases</code>.
 */
val SPECTRUM_OWID_GLOBAL_CASES: SpectrumOwidGlobalCases = SpectrumOwidGlobalCases.SPECTRUM_OWID_GLOBAL_CASES
