/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.references


import org.jooq.covspectrum.tables.SpectrumCases



/**
 * The table <code>public.spectrum_cases</code>.
 */
val SPECTRUM_CASES = SpectrumCases.SPECTRUM_CASES
