/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.references


import org.jooq.covspectrum.tables.ExtOwidGlobalCases



/**
 * The table <code>public.ext_owid_global_cases</code>.
 */
val EXT_OWID_GLOBAL_CASES = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES
