/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records


import java.time.LocalDate

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.covspectrum.tables.ExtOwidGlobalCases
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ExtOwidGlobalCasesRecord() : UpdatableRecordImpl<ExtOwidGlobalCasesRecord>(ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES), Record7<String?, String?, LocalDate?, Double?, Double?, Int?, Int?> {

    var isoCountry: String?
        set(value) = set(0, value)
        get() = get(0) as String?

    var country: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var date: LocalDate?
        set(value) = set(2, value)
        get() = get(2) as LocalDate?

    var newCasesPerMillion: Double?
        set(value) = set(3, value)
        get() = get(3) as Double?

    var newDeathsPerMillion: Double?
        set(value) = set(4, value)
        get() = get(4) as Double?

    var newCases: Int?
        set(value) = set(5, value)
        get() = get(5) as Int?

    var newDeaths: Int?
        set(value) = set(6, value)
        get() = get(6) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, LocalDate?> = super.key() as Record2<String?, LocalDate?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<String?, String?, LocalDate?, Double?, Double?, Int?, Int?> = super.fieldsRow() as Row7<String?, String?, LocalDate?, Double?, Double?, Int?, Int?>
    override fun valuesRow(): Row7<String?, String?, LocalDate?, Double?, Double?, Int?, Int?> = super.valuesRow() as Row7<String?, String?, LocalDate?, Double?, Double?, Int?, Int?>
    override fun field1(): Field<String?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.ISO_COUNTRY
    override fun field2(): Field<String?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.COUNTRY
    override fun field3(): Field<LocalDate?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.DATE
    override fun field4(): Field<Double?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.NEW_CASES_PER_MILLION
    override fun field5(): Field<Double?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.NEW_DEATHS_PER_MILLION
    override fun field6(): Field<Int?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.NEW_CASES
    override fun field7(): Field<Int?> = ExtOwidGlobalCases.EXT_OWID_GLOBAL_CASES.NEW_DEATHS
    override fun component1(): String? = isoCountry
    override fun component2(): String? = country
    override fun component3(): LocalDate? = date
    override fun component4(): Double? = newCasesPerMillion
    override fun component5(): Double? = newDeathsPerMillion
    override fun component6(): Int? = newCases
    override fun component7(): Int? = newDeaths
    override fun value1(): String? = isoCountry
    override fun value2(): String? = country
    override fun value3(): LocalDate? = date
    override fun value4(): Double? = newCasesPerMillion
    override fun value5(): Double? = newDeathsPerMillion
    override fun value6(): Int? = newCases
    override fun value7(): Int? = newDeaths

    override fun value1(value: String?): ExtOwidGlobalCasesRecord {
        this.isoCountry = value
        return this
    }

    override fun value2(value: String?): ExtOwidGlobalCasesRecord {
        this.country = value
        return this
    }

    override fun value3(value: LocalDate?): ExtOwidGlobalCasesRecord {
        this.date = value
        return this
    }

    override fun value4(value: Double?): ExtOwidGlobalCasesRecord {
        this.newCasesPerMillion = value
        return this
    }

    override fun value5(value: Double?): ExtOwidGlobalCasesRecord {
        this.newDeathsPerMillion = value
        return this
    }

    override fun value6(value: Int?): ExtOwidGlobalCasesRecord {
        this.newCases = value
        return this
    }

    override fun value7(value: Int?): ExtOwidGlobalCasesRecord {
        this.newDeaths = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: LocalDate?, value4: Double?, value5: Double?, value6: Int?, value7: Int?): ExtOwidGlobalCasesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised ExtOwidGlobalCasesRecord
     */
    constructor(isoCountry: String? = null, country: String? = null, date: LocalDate? = null, newCasesPerMillion: Double? = null, newDeathsPerMillion: Double? = null, newCases: Int? = null, newDeaths: Int? = null): this() {
        this.isoCountry = isoCountry
        this.country = country
        this.date = date
        this.newCasesPerMillion = newCasesPerMillion
        this.newDeathsPerMillion = newDeathsPerMillion
        this.newCases = newCases
        this.newDeaths = newDeaths
    }
}
