/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records


import java.time.LocalDate

import org.jooq.Field
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.covspectrum.tables.SpectrumCases
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SpectrumCasesRecord() : TableRecordImpl<SpectrumCasesRecord>(SpectrumCases.SPECTRUM_CASES), Record6<String?, String?, String?, LocalDate?, Long?, Int?> {

    var region: String?
        set(value) = set(0, value)
        get() = get(0) as String?

    var country: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var division: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var date: LocalDate?
        set(value) = set(3, value)
        get() = get(3) as LocalDate?

    var newCases: Long?
        set(value) = set(4, value)
        get() = get(4) as Long?

    var newDeaths: Int?
        set(value) = set(5, value)
        get() = get(5) as Int?

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<String?, String?, String?, LocalDate?, Long?, Int?> = super.fieldsRow() as Row6<String?, String?, String?, LocalDate?, Long?, Int?>
    override fun valuesRow(): Row6<String?, String?, String?, LocalDate?, Long?, Int?> = super.valuesRow() as Row6<String?, String?, String?, LocalDate?, Long?, Int?>
    override fun field1(): Field<String?> = SpectrumCases.SPECTRUM_CASES.REGION
    override fun field2(): Field<String?> = SpectrumCases.SPECTRUM_CASES.COUNTRY
    override fun field3(): Field<String?> = SpectrumCases.SPECTRUM_CASES.DIVISION
    override fun field4(): Field<LocalDate?> = SpectrumCases.SPECTRUM_CASES.DATE
    override fun field5(): Field<Long?> = SpectrumCases.SPECTRUM_CASES.NEW_CASES
    override fun field6(): Field<Int?> = SpectrumCases.SPECTRUM_CASES.NEW_DEATHS
    override fun component1(): String? = region
    override fun component2(): String? = country
    override fun component3(): String? = division
    override fun component4(): LocalDate? = date
    override fun component5(): Long? = newCases
    override fun component6(): Int? = newDeaths
    override fun value1(): String? = region
    override fun value2(): String? = country
    override fun value3(): String? = division
    override fun value4(): LocalDate? = date
    override fun value5(): Long? = newCases
    override fun value6(): Int? = newDeaths

    override fun value1(value: String?): SpectrumCasesRecord {
        this.region = value
        return this
    }

    override fun value2(value: String?): SpectrumCasesRecord {
        this.country = value
        return this
    }

    override fun value3(value: String?): SpectrumCasesRecord {
        this.division = value
        return this
    }

    override fun value4(value: LocalDate?): SpectrumCasesRecord {
        this.date = value
        return this
    }

    override fun value5(value: Long?): SpectrumCasesRecord {
        this.newCases = value
        return this
    }

    override fun value6(value: Int?): SpectrumCasesRecord {
        this.newDeaths = value
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: LocalDate?, value5: Long?, value6: Int?): SpectrumCasesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised SpectrumCasesRecord
     */
    constructor(region: String? = null, country: String? = null, division: String? = null, date: LocalDate? = null, newCases: Long? = null, newDeaths: Int? = null): this() {
        this.region = region
        this.country = country
        this.division = division
        this.date = date
        this.newCases = newCases
        this.newDeaths = newDeaths
    }
}
