/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.covspectrum.tables.PangolinLineage_PubmedArticle;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PangolinLineage_PubmedArticleRecord extends TableRecordImpl<PangolinLineage_PubmedArticleRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pangolin_lineage__pubmed_article.pangolin_lineage</code>.
     */
    public void setPangolinLineage(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pangolin_lineage__pubmed_article.pangolin_lineage</code>.
     */
    public String getPangolinLineage() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.pangolin_lineage__pubmed_article.pmid</code>.
     */
    public void setPmid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pangolin_lineage__pubmed_article.pmid</code>.
     */
    public Long getPmid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PangolinLineage_PubmedArticle.PANGOLIN_LINEAGE__PUBMED_ARTICLE.PANGOLIN_LINEAGE;
    }

    @Override
    public Field<Long> field2() {
        return PangolinLineage_PubmedArticle.PANGOLIN_LINEAGE__PUBMED_ARTICLE.PMID;
    }

    @Override
    public String component1() {
        return getPangolinLineage();
    }

    @Override
    public Long component2() {
        return getPmid();
    }

    @Override
    public String value1() {
        return getPangolinLineage();
    }

    @Override
    public Long value2() {
        return getPmid();
    }

    @Override
    public PangolinLineage_PubmedArticleRecord value1(String value) {
        setPangolinLineage(value);
        return this;
    }

    @Override
    public PangolinLineage_PubmedArticleRecord value2(Long value) {
        setPmid(value);
        return this;
    }

    @Override
    public PangolinLineage_PubmedArticleRecord values(String value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PangolinLineage_PubmedArticleRecord
     */
    public PangolinLineage_PubmedArticleRecord() {
        super(PangolinLineage_PubmedArticle.PANGOLIN_LINEAGE__PUBMED_ARTICLE);
    }

    /**
     * Create a detached, initialised PangolinLineage_PubmedArticleRecord
     */
    public PangolinLineage_PubmedArticleRecord(String pangolinLineage, Long pmid) {
        super(PangolinLineage_PubmedArticle.PANGOLIN_LINEAGE__PUBMED_ARTICLE);

        setPangolinLineage(pangolinLineage);
        setPmid(pmid);
    }
}
