/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.covspectrum.tables.PangolinLineage_RxivArticle;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PangolinLineage_RxivArticleRecord extends TableRecordImpl<PangolinLineage_RxivArticleRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pangolin_lineage__rxiv_article.pangolin_lineage</code>.
     */
    public void setPangolinLineage(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pangolin_lineage__rxiv_article.pangolin_lineage</code>.
     */
    public String getPangolinLineage() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.pangolin_lineage__rxiv_article.doi</code>.
     */
    public void setDoi(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pangolin_lineage__rxiv_article.doi</code>.
     */
    public String getDoi() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PangolinLineage_RxivArticle.PANGOLIN_LINEAGE__RXIV_ARTICLE.PANGOLIN_LINEAGE;
    }

    @Override
    public Field<String> field2() {
        return PangolinLineage_RxivArticle.PANGOLIN_LINEAGE__RXIV_ARTICLE.DOI;
    }

    @Override
    public String component1() {
        return getPangolinLineage();
    }

    @Override
    public String component2() {
        return getDoi();
    }

    @Override
    public String value1() {
        return getPangolinLineage();
    }

    @Override
    public String value2() {
        return getDoi();
    }

    @Override
    public PangolinLineage_RxivArticleRecord value1(String value) {
        setPangolinLineage(value);
        return this;
    }

    @Override
    public PangolinLineage_RxivArticleRecord value2(String value) {
        setDoi(value);
        return this;
    }

    @Override
    public PangolinLineage_RxivArticleRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PangolinLineage_RxivArticleRecord
     */
    public PangolinLineage_RxivArticleRecord() {
        super(PangolinLineage_RxivArticle.PANGOLIN_LINEAGE__RXIV_ARTICLE);
    }

    /**
     * Create a detached, initialised PangolinLineage_RxivArticleRecord
     */
    public PangolinLineage_RxivArticleRecord(String pangolinLineage, String doi) {
        super(PangolinLineage_RxivArticle.PANGOLIN_LINEAGE__RXIV_ARTICLE);

        setPangolinLineage(pangolinLineage);
        setDoi(doi);
    }
}
