/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.covspectrum.tables.SpectrumSequenceIntensity;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumSequenceIntensityRecord extends TableRecordImpl<SpectrumSequenceIntensityRecord> implements Record4<String, LocalDate, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_sequence_intensity.country</code>.
     */
    public void setCountry(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_intensity.country</code>.
     */
    public String getCountry() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_sequence_intensity.date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_intensity.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.spectrum_sequence_intensity.sequenced</code>.
     */
    public void setSequenced(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_intensity.sequenced</code>.
     */
    public Long getSequenced() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.spectrum_sequence_intensity.cases</code>.
     */
    public void setCases(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_intensity.cases</code>.
     */
    public Integer getCases() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, LocalDate, Long, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, LocalDate, Long, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY.COUNTRY;
    }

    @Override
    public Field<LocalDate> field2() {
        return SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY.DATE;
    }

    @Override
    public Field<Long> field3() {
        return SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY.SEQUENCED;
    }

    @Override
    public Field<Integer> field4() {
        return SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY.CASES;
    }

    @Override
    public String component1() {
        return getCountry();
    }

    @Override
    public LocalDate component2() {
        return getDate();
    }

    @Override
    public Long component3() {
        return getSequenced();
    }

    @Override
    public Integer component4() {
        return getCases();
    }

    @Override
    public String value1() {
        return getCountry();
    }

    @Override
    public LocalDate value2() {
        return getDate();
    }

    @Override
    public Long value3() {
        return getSequenced();
    }

    @Override
    public Integer value4() {
        return getCases();
    }

    @Override
    public SpectrumSequenceIntensityRecord value1(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public SpectrumSequenceIntensityRecord value2(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public SpectrumSequenceIntensityRecord value3(Long value) {
        setSequenced(value);
        return this;
    }

    @Override
    public SpectrumSequenceIntensityRecord value4(Integer value) {
        setCases(value);
        return this;
    }

    @Override
    public SpectrumSequenceIntensityRecord values(String value1, LocalDate value2, Long value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumSequenceIntensityRecord
     */
    public SpectrumSequenceIntensityRecord() {
        super(SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY);
    }

    /**
     * Create a detached, initialised SpectrumSequenceIntensityRecord
     */
    public SpectrumSequenceIntensityRecord(String country, LocalDate date, Long sequenced, Integer cases) {
        super(SpectrumSequenceIntensity.SPECTRUM_SEQUENCE_INTENSITY);

        setCountry(country);
        setDate(date);
        setSequenced(sequenced);
        setCases(cases);
    }
}
