/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.covspectrum.tables.SpectrumPangolinLineageMutation;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumPangolinLineageMutationRecord extends TableRecordImpl<SpectrumPangolinLineageMutationRecord> implements Record6<String, String, LocalDate, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.region</code>.
     */
    public void setRegion(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.region</code>.
     */
    public String getRegion() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.country</code>.
     */
    public void setCountry(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.country</code>.
     */
    public String getCountry() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.pangolin_lineage</code>.
     */
    public void setPangolinLineage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.pangolin_lineage</code>.
     */
    public String getPangolinLineage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.aa_mutation</code>.
     */
    public void setAaMutation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.aa_mutation</code>.
     */
    public String getAaMutation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.spectrum_pangolin_lineage_mutation.count</code>.
     */
    public void setCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.spectrum_pangolin_lineage_mutation.count</code>.
     */
    public Long getCount() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, LocalDate, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, LocalDate, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.REGION;
    }

    @Override
    public Field<String> field2() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.COUNTRY;
    }

    @Override
    public Field<LocalDate> field3() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.DATE;
    }

    @Override
    public Field<String> field4() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.PANGOLIN_LINEAGE;
    }

    @Override
    public Field<String> field5() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.AA_MUTATION;
    }

    @Override
    public Field<Long> field6() {
        return SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION.COUNT;
    }

    @Override
    public String component1() {
        return getRegion();
    }

    @Override
    public String component2() {
        return getCountry();
    }

    @Override
    public LocalDate component3() {
        return getDate();
    }

    @Override
    public String component4() {
        return getPangolinLineage();
    }

    @Override
    public String component5() {
        return getAaMutation();
    }

    @Override
    public Long component6() {
        return getCount();
    }

    @Override
    public String value1() {
        return getRegion();
    }

    @Override
    public String value2() {
        return getCountry();
    }

    @Override
    public LocalDate value3() {
        return getDate();
    }

    @Override
    public String value4() {
        return getPangolinLineage();
    }

    @Override
    public String value5() {
        return getAaMutation();
    }

    @Override
    public Long value6() {
        return getCount();
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value1(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value2(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value3(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value4(String value) {
        setPangolinLineage(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value5(String value) {
        setAaMutation(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord value6(Long value) {
        setCount(value);
        return this;
    }

    @Override
    public SpectrumPangolinLineageMutationRecord values(String value1, String value2, LocalDate value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumPangolinLineageMutationRecord
     */
    public SpectrumPangolinLineageMutationRecord() {
        super(SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION);
    }

    /**
     * Create a detached, initialised SpectrumPangolinLineageMutationRecord
     */
    public SpectrumPangolinLineageMutationRecord(String region, String country, LocalDate date, String pangolinLineage, String aaMutation, Long count) {
        super(SpectrumPangolinLineageMutation.SPECTRUM_PANGOLIN_LINEAGE_MUTATION);

        setRegion(region);
        setCountry(country);
        setDate(date);
        setPangolinLineage(pangolinLineage);
        setAaMutation(aaMutation);
        setCount(count);
    }
}
