/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMutationAa;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumSequencePublicMutationAaRecord extends TableRecordImpl<SpectrumSequencePublicMutationAaRecord> implements Record5<String, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.sequence_name</code>.
     */
    public void setSequenceName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.sequence_name</code>.
     */
    public String getSequenceName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation</code>.
     */
    public void setAaMutation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation</code>.
     */
    public String getAaMutation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_gene</code>.
     */
    public void setAaMutationGene(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_gene</code>.
     */
    public String getAaMutationGene() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_position</code>.
     */
    public void setAaMutationPosition(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_position</code>.
     */
    public Integer getAaMutationPosition() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_base</code>.
     */
    public void setAaMutationBase(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation_base</code>.
     */
    public String getAaMutationBase() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.SEQUENCE_NAME;
    }

    @Override
    public Field<String> field2() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION;
    }

    @Override
    public Field<String> field3() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION_GENE;
    }

    @Override
    public Field<Integer> field4() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION_POSITION;
    }

    @Override
    public Field<String> field5() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION_BASE;
    }

    @Override
    public String component1() {
        return getSequenceName();
    }

    @Override
    public String component2() {
        return getAaMutation();
    }

    @Override
    public String component3() {
        return getAaMutationGene();
    }

    @Override
    public Integer component4() {
        return getAaMutationPosition();
    }

    @Override
    public String component5() {
        return getAaMutationBase();
    }

    @Override
    public String value1() {
        return getSequenceName();
    }

    @Override
    public String value2() {
        return getAaMutation();
    }

    @Override
    public String value3() {
        return getAaMutationGene();
    }

    @Override
    public Integer value4() {
        return getAaMutationPosition();
    }

    @Override
    public String value5() {
        return getAaMutationBase();
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value1(String value) {
        setSequenceName(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value2(String value) {
        setAaMutation(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value3(String value) {
        setAaMutationGene(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value4(Integer value) {
        setAaMutationPosition(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value5(String value) {
        setAaMutationBase(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord values(String value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumSequencePublicMutationAaRecord
     */
    public SpectrumSequencePublicMutationAaRecord() {
        super(SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA);
    }

    /**
     * Create a detached, initialised SpectrumSequencePublicMutationAaRecord
     */
    public SpectrumSequencePublicMutationAaRecord(String sequenceName, String aaMutation, String aaMutationGene, Integer aaMutationPosition, String aaMutationBase) {
        super(SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA);

        setSequenceName(sequenceName);
        setAaMutation(aaMutation);
        setAaMutationGene(aaMutationGene);
        setAaMutationPosition(aaMutationPosition);
        setAaMutationBase(aaMutationBase);
    }
}
