/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.covspectrum.tables.SpectrumCountry;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumCountryRecord extends UpdatableRecordImpl<SpectrumCountryRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_country.iso_code</code>.
     */
    public void setIsoCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_country.iso_code</code>.
     */
    public String getIsoCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_country.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_country.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spectrum_country.region</code>.
     */
    public void setRegion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_country.region</code>.
     */
    public String getRegion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.spectrum_country.url_component</code>.
     */
    public void setUrlComponent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spectrum_country.url_component</code>.
     */
    public String getUrlComponent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.spectrum_country.fiv_resource_category</code>.
     */
    public void setFivResourceCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spectrum_country.fiv_resource_category</code>.
     */
    public String getFivResourceCategory() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumCountry.SPECTRUM_COUNTRY.ISO_CODE;
    }

    @Override
    public Field<String> field2() {
        return SpectrumCountry.SPECTRUM_COUNTRY.NAME;
    }

    @Override
    public Field<String> field3() {
        return SpectrumCountry.SPECTRUM_COUNTRY.REGION;
    }

    @Override
    public Field<String> field4() {
        return SpectrumCountry.SPECTRUM_COUNTRY.URL_COMPONENT;
    }

    @Override
    public Field<String> field5() {
        return SpectrumCountry.SPECTRUM_COUNTRY.FIV_RESOURCE_CATEGORY;
    }

    @Override
    public String component1() {
        return getIsoCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getRegion();
    }

    @Override
    public String component4() {
        return getUrlComponent();
    }

    @Override
    public String component5() {
        return getFivResourceCategory();
    }

    @Override
    public String value1() {
        return getIsoCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getRegion();
    }

    @Override
    public String value4() {
        return getUrlComponent();
    }

    @Override
    public String value5() {
        return getFivResourceCategory();
    }

    @Override
    public SpectrumCountryRecord value1(String value) {
        setIsoCode(value);
        return this;
    }

    @Override
    public SpectrumCountryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SpectrumCountryRecord value3(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public SpectrumCountryRecord value4(String value) {
        setUrlComponent(value);
        return this;
    }

    @Override
    public SpectrumCountryRecord value5(String value) {
        setFivResourceCategory(value);
        return this;
    }

    @Override
    public SpectrumCountryRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumCountryRecord
     */
    public SpectrumCountryRecord() {
        super(SpectrumCountry.SPECTRUM_COUNTRY);
    }

    /**
     * Create a detached, initialised SpectrumCountryRecord
     */
    public SpectrumCountryRecord(String isoCode, String name, String region, String urlComponent, String fivResourceCategory) {
        super(SpectrumCountry.SPECTRUM_COUNTRY);

        setIsoCode(isoCode);
        setName(name);
        setRegion(region);
        setUrlComponent(urlComponent);
        setFivResourceCategory(fivResourceCategory);
    }
}
