/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.covspectrum.tables.SpectrumApiUsageSample;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumApiUsageSampleRecord extends UpdatableRecordImpl<SpectrumApiUsageSampleRecord> implements Record14<Integer, Integer, Integer, Integer, String, Boolean, String, String, String, Double, String, LocalDate, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_api_usage_sample.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.isoyear</code>.
     */
    public void setIsoyear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.isoyear</code>.
     */
    public Integer getIsoyear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.isoweek</code>.
     */
    public void setIsoweek(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.isoweek</code>.
     */
    public Integer getIsoweek() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.usage_count</code>.
     */
    public void setUsageCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.usage_count</code>.
     */
    public Integer getUsageCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.fields</code>.
     */
    public void setFields(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.fields</code>.
     */
    public String getFields() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.private_version</code>.
     */
    public void setPrivateVersion(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.private_version</code>.
     */
    public Boolean getPrivateVersion() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.region</code>.
     */
    public void setRegion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.region</code>.
     */
    public String getRegion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.mutations</code>.
     */
    public void setMutations(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.mutations</code>.
     */
    public String getMutations() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.match_percentage</code>.
     */
    public void setMatchPercentage(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.match_percentage</code>.
     */
    public Double getMatchPercentage() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.data_type</code>.
     */
    public void setDataType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.data_type</code>.
     */
    public String getDataType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.date_from</code>.
     */
    public void setDateFrom(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.date_from</code>.
     */
    public LocalDate getDateFrom() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.date_to</code>.
     */
    public void setDateTo(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.date_to</code>.
     */
    public LocalDate getDateTo() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>public.spectrum_api_usage_sample.pangolin_lineage</code>.
     */
    public void setPangolinLineage(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.spectrum_api_usage_sample.pangolin_lineage</code>.
     */
    public String getPangolinLineage() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, Integer, Integer, String, Boolean, String, String, String, Double, String, LocalDate, LocalDate, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, Integer, Integer, Integer, String, Boolean, String, String, String, Double, String, LocalDate, LocalDate, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.ISOYEAR;
    }

    @Override
    public Field<Integer> field3() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.ISOWEEK;
    }

    @Override
    public Field<Integer> field4() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.USAGE_COUNT;
    }

    @Override
    public Field<String> field5() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.FIELDS;
    }

    @Override
    public Field<Boolean> field6() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.PRIVATE_VERSION;
    }

    @Override
    public Field<String> field7() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.REGION;
    }

    @Override
    public Field<String> field8() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.COUNTRY;
    }

    @Override
    public Field<String> field9() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.MUTATIONS;
    }

    @Override
    public Field<Double> field10() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.MATCH_PERCENTAGE;
    }

    @Override
    public Field<String> field11() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.DATA_TYPE;
    }

    @Override
    public Field<LocalDate> field12() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.DATE_FROM;
    }

    @Override
    public Field<LocalDate> field13() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.DATE_TO;
    }

    @Override
    public Field<String> field14() {
        return SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE.PANGOLIN_LINEAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getIsoyear();
    }

    @Override
    public Integer component3() {
        return getIsoweek();
    }

    @Override
    public Integer component4() {
        return getUsageCount();
    }

    @Override
    public String component5() {
        return getFields();
    }

    @Override
    public Boolean component6() {
        return getPrivateVersion();
    }

    @Override
    public String component7() {
        return getRegion();
    }

    @Override
    public String component8() {
        return getCountry();
    }

    @Override
    public String component9() {
        return getMutations();
    }

    @Override
    public Double component10() {
        return getMatchPercentage();
    }

    @Override
    public String component11() {
        return getDataType();
    }

    @Override
    public LocalDate component12() {
        return getDateFrom();
    }

    @Override
    public LocalDate component13() {
        return getDateTo();
    }

    @Override
    public String component14() {
        return getPangolinLineage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getIsoyear();
    }

    @Override
    public Integer value3() {
        return getIsoweek();
    }

    @Override
    public Integer value4() {
        return getUsageCount();
    }

    @Override
    public String value5() {
        return getFields();
    }

    @Override
    public Boolean value6() {
        return getPrivateVersion();
    }

    @Override
    public String value7() {
        return getRegion();
    }

    @Override
    public String value8() {
        return getCountry();
    }

    @Override
    public String value9() {
        return getMutations();
    }

    @Override
    public Double value10() {
        return getMatchPercentage();
    }

    @Override
    public String value11() {
        return getDataType();
    }

    @Override
    public LocalDate value12() {
        return getDateFrom();
    }

    @Override
    public LocalDate value13() {
        return getDateTo();
    }

    @Override
    public String value14() {
        return getPangolinLineage();
    }

    @Override
    public SpectrumApiUsageSampleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value2(Integer value) {
        setIsoyear(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value3(Integer value) {
        setIsoweek(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value4(Integer value) {
        setUsageCount(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value5(String value) {
        setFields(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value6(Boolean value) {
        setPrivateVersion(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value7(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value8(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value9(String value) {
        setMutations(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value10(Double value) {
        setMatchPercentage(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value11(String value) {
        setDataType(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value12(LocalDate value) {
        setDateFrom(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value13(LocalDate value) {
        setDateTo(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord value14(String value) {
        setPangolinLineage(value);
        return this;
    }

    @Override
    public SpectrumApiUsageSampleRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, Boolean value6, String value7, String value8, String value9, Double value10, String value11, LocalDate value12, LocalDate value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumApiUsageSampleRecord
     */
    public SpectrumApiUsageSampleRecord() {
        super(SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE);
    }

    /**
     * Create a detached, initialised SpectrumApiUsageSampleRecord
     */
    public SpectrumApiUsageSampleRecord(Integer id, Integer isoyear, Integer isoweek, Integer usageCount, String fields, Boolean privateVersion, String region, String country, String mutations, Double matchPercentage, String dataType, LocalDate dateFrom, LocalDate dateTo, String pangolinLineage) {
        super(SpectrumApiUsageSample.SPECTRUM_API_USAGE_SAMPLE);

        setId(id);
        setIsoyear(isoyear);
        setIsoweek(isoweek);
        setUsageCount(usageCount);
        setFields(fields);
        setPrivateVersion(privateVersion);
        setRegion(region);
        setCountry(country);
        setMutations(mutations);
        setMatchPercentage(matchPercentage);
        setDataType(dataType);
        setDateFrom(dateFrom);
        setDateTo(dateTo);
        setPangolinLineage(pangolinLineage);
    }
}
