/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.covspectrum.tables.SpectrumSequencePublicMutationAa;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumSequencePublicMutationAaRecord extends TableRecordImpl<SpectrumSequencePublicMutationAaRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.sequence_name</code>.
     */
    public void setSequenceName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.sequence_name</code>.
     */
    public String getSequenceName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation</code>.
     */
    public void setAaMutation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_sequence_public_mutation_aa.aa_mutation</code>.
     */
    public String getAaMutation() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.SEQUENCE_NAME;
    }

    @Override
    public Field<String> field2() {
        return SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA.AA_MUTATION;
    }

    @Override
    public String component1() {
        return getSequenceName();
    }

    @Override
    public String component2() {
        return getAaMutation();
    }

    @Override
    public String value1() {
        return getSequenceName();
    }

    @Override
    public String value2() {
        return getAaMutation();
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value1(String value) {
        setSequenceName(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord value2(String value) {
        setAaMutation(value);
        return this;
    }

    @Override
    public SpectrumSequencePublicMutationAaRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumSequencePublicMutationAaRecord
     */
    public SpectrumSequencePublicMutationAaRecord() {
        super(SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA);
    }

    /**
     * Create a detached, initialised SpectrumSequencePublicMutationAaRecord
     */
    public SpectrumSequencePublicMutationAaRecord(String sequenceName, String aaMutation) {
        super(SpectrumSequencePublicMutationAa.SPECTRUM_SEQUENCE_PUBLIC_MUTATION_AA);

        setSequenceName(sequenceName);
        setAaMutation(aaMutation);
    }
}
