/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.covspectrum.tables.SpectrumAccount;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumAccountRecord extends UpdatableRecordImpl<SpectrumAccountRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_account.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_account.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_account.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_account.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spectrum_account.full_name</code>.
     */
    public void setFullName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_account.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumAccount.SPECTRUM_ACCOUNT.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return SpectrumAccount.SPECTRUM_ACCOUNT.PASSWORD_HASH;
    }

    @Override
    public Field<String> field3() {
        return SpectrumAccount.SPECTRUM_ACCOUNT.FULL_NAME;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getPasswordHash();
    }

    @Override
    public String component3() {
        return getFullName();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getPasswordHash();
    }

    @Override
    public String value3() {
        return getFullName();
    }

    @Override
    public SpectrumAccountRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public SpectrumAccountRecord value2(String value) {
        setPasswordHash(value);
        return this;
    }

    @Override
    public SpectrumAccountRecord value3(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public SpectrumAccountRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumAccountRecord
     */
    public SpectrumAccountRecord() {
        super(SpectrumAccount.SPECTRUM_ACCOUNT);
    }

    /**
     * Create a detached, initialised SpectrumAccountRecord
     */
    public SpectrumAccountRecord(String username, String passwordHash, String fullName) {
        super(SpectrumAccount.SPECTRUM_ACCOUNT);

        setUsername(username);
        setPasswordHash(passwordHash);
        setFullName(fullName);
    }
}
