/*
 * This file is generated by jOOQ.
 */
package org.jooq.covspectrum.tables.records;


import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.covspectrum.tables.SpectrumWasteWaterResult;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpectrumWasteWaterResultRecord extends UpdatableRecordImpl<SpectrumWasteWaterResultRecord> implements Record3<String, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.spectrum_waste_water_result.variant_name</code>.
     */
    public void setVariantName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.spectrum_waste_water_result.variant_name</code>.
     */
    public String getVariantName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.spectrum_waste_water_result.location</code>.
     */
    public void setLocation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.spectrum_waste_water_result.location</code>.
     */
    public String getLocation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.spectrum_waste_water_result.data</code>.
     */
    public void setData(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.spectrum_waste_water_result.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, JSONB> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SpectrumWasteWaterResult.SPECTRUM_WASTE_WATER_RESULT.VARIANT_NAME;
    }

    @Override
    public Field<String> field2() {
        return SpectrumWasteWaterResult.SPECTRUM_WASTE_WATER_RESULT.LOCATION;
    }

    @Override
    public Field<JSONB> field3() {
        return SpectrumWasteWaterResult.SPECTRUM_WASTE_WATER_RESULT.DATA;
    }

    @Override
    public String component1() {
        return getVariantName();
    }

    @Override
    public String component2() {
        return getLocation();
    }

    @Override
    public JSONB component3() {
        return getData();
    }

    @Override
    public String value1() {
        return getVariantName();
    }

    @Override
    public String value2() {
        return getLocation();
    }

    @Override
    public JSONB value3() {
        return getData();
    }

    @Override
    public SpectrumWasteWaterResultRecord value1(String value) {
        setVariantName(value);
        return this;
    }

    @Override
    public SpectrumWasteWaterResultRecord value2(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public SpectrumWasteWaterResultRecord value3(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public SpectrumWasteWaterResultRecord values(String value1, String value2, JSONB value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpectrumWasteWaterResultRecord
     */
    public SpectrumWasteWaterResultRecord() {
        super(SpectrumWasteWaterResult.SPECTRUM_WASTE_WATER_RESULT);
    }

    /**
     * Create a detached, initialised SpectrumWasteWaterResultRecord
     */
    public SpectrumWasteWaterResultRecord(String variantName, String location, JSONB data) {
        super(SpectrumWasteWaterResult.SPECTRUM_WASTE_WATER_RESULT);

        setVariantName(variantName);
        setLocation(location);
        setData(data);
    }
}
