name: Docker (ingest-pangoLineageAliases)

on:
  workflow_dispatch:
  push:
    branches:
    paths:
      - 'ext_models/ingest-pangoLineageAliases/**'

env:
  IMAGE_NAME: ghcr.io/cevo-public/cov-spectrum-ingest-pangolineagealiases

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable "BRANCH"
        run: |
          echo "BRANCH=$(eval 'echo $GITHUB_REF | sed s/refs\\/heads\\/// | sed s/\\//__/ ')" >> $GITHUB_ENV
      - name: Build image
        run: |
          cd ext_models/ingest-pangoLineageAliases
          docker build -t new_image .
      - name: Login to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Add tags and push
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
          docker push ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
          docker tag new_image ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
      - name: Add "develop" tag and push
        if: env.BRANCH == 'develop'
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:develop
          docker push ${{ env.IMAGE_NAME }}:develop
      - name: Add "public" tag and push
        if: env.BRANCH == 'public'
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:public
          docker push ${{ env.IMAGE_NAME }}:public
